### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
@bilgili: I now get a black rendering and am a bit lost on how to fix it. You can activate the GL2 renderer on Linux using 'cmake -DLIVRE_USE_GL2=ON' - can you have a look?

**Comment by bilgili** [comment]
yep, I can have a look tomorrow

**Comment by eile** [comment]
retest this please.

**Comment by eile** [comment]
Ping @rdumusc @chevtche

**Pull request merged**
