### PR TITLE
cppcheck fixes

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
Do you think this commit is complete ?

**Comment by rdumusc** [comment]
Needs (at least) an Equalizer update after https://github.com/Eyescale/Equalizer/pull/486 is merged

**Comment by rdumusc** [comment]
+1. I'm surprised it didn't need a Lunchbox update like the other projects, but as long as it works...

**Pull request merged**
