### PR TITLE
Enable Travis

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
Do not merge yet

**Comment by eile** [comment]
@bilgili: Do you have an idea why this fails: https://travis-ci.org/eile/Livre/jobs/126397424#L424

**Comment by eile** [comment]
@bilgili : I had a shot at the test failure: 859f56e. Not sure about the resolution, please have a look.

**Comment by eile** [comment]
But the old implementation did clean up everything (size < 0 * max is always false in hasSpace)?

**Comment by eile** [comment]
ping

**Comment by bilgili** [comment]
+1

**Pull request merged**
