### PR TITLE
Write png's if SATTR_DUMP_IMAGE and fill with 0's to ease movie gener…

### PR DESCRIPTION
**Pull request by tribal-tec**
…ation

Needs https://github.com/Eyescale/Equalizer/pull/461 to work

FYI @chevtche

### CODE REVIEW

**Comment by tribal-tec** [comment]
Need to adapt livre_batch.py as well. Image numbering changed...

**Comment by tribal-tec** [comment]
Ok, script is fixed.

**Comment by eile** [comment]
+1

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
