### PR TITLE
Clean up UI, mostly color map editor

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
@favreau FYI

**Comment by eile** [comment]
Before/After:
before
after

**Comment by jafyvilla** [comment]
+1

**Comment by eile** [comment]
@chevtche FYI

**Comment by eile** [comment]
For the demo is it not needed. All applications should use the same scheme. You then want a selection UI with application, user and host and not choose which (zeroconf) publisher you want to subscribe to.

**Comment by bilgili** [comment]
I am still not convinced about removing it unless the alternative you mention, or another alternative is there. Lets discuss later, because to me  if it is "for the demo"  it should be a discardable branch, not the master branch.

**Comment by eile** [comment]
Let's discuss in person after the Summit. We have danced around this issue for over a year without addressing it, so this is a way to force it to happen. Doing a wrong thing to fix another wrong thing is not good.

**Pull request merged**
