### PR TITLE
Exit gracefully when zeq exit event is received

### PR DESCRIPTION
**Pull request by bilgili**

### CODE REVIEW

**Comment by bilgili** [comment]
I messed up things, so while fixing github removed the pull request. Sorry.

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by eile** [comment]
CR in #21

**Pull request merged**
