### PR TITLE
LivreGUI uses QDockWidgets instead of tabs

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by rdumusc** [comment]
livregui

**Comment by jafyvilla** [comment]
Awesome improvement! +1

**Comment by bilgili** [comment]
Dockwidgets part is awesome though.

**Comment by rdumusc** [comment]
@bilgili Yes, we will need a dedicated panel for setting the Zeq connections. It should let the user choose from the results of the ZeroConf auto-discovery, and allow to enter a manual address as a fallback. Maybe I can work on this tomorrow depending on other priorities. But for the immediate needs of the summit demo, the hardcoded version should do the job.

**Comment by bilgili** [comment]
No more comments from me :) Giving my blessing, but still thinking the same.

**Pull request merged**
