### PR TITLE
Disable RESTBridge on MSVC

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by bilgili** [comment]
Why dont we enforce RESTBridge to be fixed ?

**Comment by eile** [comment]
We do, but I'ld also like to get the Fivox CR merged at some point. @chevtche is working on the RESTBridge.

**Comment by eile** [comment]
retest this please

**Comment by eile** [comment]
retest this please

**Comment by eile** [comment]
retest this please

**Comment by bilgili** [comment]
Closing pull request ?

**Comment by tribal-tec** [comment]
No. I can confirm, that cppnetlib does not build out-of-the box on Windows.

**Comment by bilgili** [comment]
retest this please

**Comment by eile** [comment]
retest this please

**Comment by rdumusc** [comment]
Watch out - the .gitexternals in this PR is now going backwards after https://github.com/BlueBrain/Livre/pull/94 was merged

**Comment by eile** [comment]
@rdumusc: I paid attention to use the same SHA1 as master?!

All: retest this please does not work on this repo. Ticket is opened. I used the same SHA as master for .gitexternals and the moved RESTBridge sub project - ok to merge as is?

**Comment by rdumusc** [comment]
eyescale/cmake master is currently 93b3c07. Livre .gitexternals currenly contains ac0f882. Your PR goes back to 74a67ee because it has been open for quite some time, and needs rebasing anyway because github cannot merge.

**Comment by eile** [comment]
And still the diff in this PR shows the same SHA1 for both .gitexternals. sigh. Will investigate.

**Comment by eile** [comment]
Fixed - merge or not?

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
+1 for me. I'm wondering if this simple change is ever going to compile, I count 10 failed tests already... last hope then merge anyway ;-)

**Comment by bilgili** [comment]
waiting build !

**Comment by rdumusc** [comment]
Jenkins timeout - is address by my other pull request. 3/4 succeeded so good to merge for me.

**Pull request merged**
