### PR TITLE
Fixes blocking when data is already available for rendering

### PR DESCRIPTION
**Pull request by jafyvilla**

### CODE REVIEW

**Comment by bilgili** [comment]
please retest this

**Comment by jafyvilla** [comment]
Retest this please

**Comment by bilgili** [comment]
Retest this please

**Comment by bilgili** [comment]
Woohoooo, the building errors seems ... !

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by bilgili** [comment]
retest this please

**Comment by eile** [comment]
Can we fix the failing tests, please?

**Comment by bilgili** [comment]
Will be fixed by cyrill.

**Comment by eile** [comment]
Ok, good.

Nobody CR'd this!?

**Comment by bilgili** [comment]
- We have checked with @jafyvilla before you guys left for HBP.
- I feel lucky when I have code reviews these days.
- Is there a problem ?

**Comment by jafyvilla** [comment]
Yes, it's one of those fixes added last minute before leaving. It was reviewed in person, I should have said something here for the record...

**Comment by eile** [comment]
Ok, no worries. I just saw the wall of 'retest this' ;)

**Pull request merged**
