### PR TITLE
Add follow-data option to animation mode

### PR DESCRIPTION
**Pull request by rdumusc**

### CODE REVIEW

**Comment by rdumusc** [comment]
retest this please

**Comment by bilgili** [comment]
Changelog

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
Works with MemoryDataSource, but when used with Fivox and Nest most frames are black. This needs further investigation to understand the cause of the problem.

**Comment by rdumusc** [comment]
retest this please

**Comment by bilgili** [comment]
Have you tested this with streaming data sources ;)

**Comment by jafyvilla** [comment]
+1

**Comment by bilgili** [comment]
Until Fivox change [https://bbpcode.epfl.ch/code/#/c/17632] is cleared out, I will wait to merge.

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
This code has been tested to work with or without a change in Fivox. It is also independent of the pending Brion+Monsteer changes.

**Comment by bilgili** [comment]
Ok !

**Pull request merged**
