### PR TITLE
OSX Fix

### PR DESCRIPTION
**Pull request by bilgili**
FYI @eile , GL3 is fine with OSX as far as I have seen.

### CODE REVIEW

**Comment by eile** [comment]
Not sure, trying this PR right now. IIRC X11 has GL 2.1 and is needed for 64 bit executables.

**Comment by eile** [comment]
yep: ```GLSLShaders.cpp:62     1743 Shader error: ERROR: 0:7: '' :  version '130' is not supported```

-1 from me. ;)

**Comment by bilgili** [comment]
this is a shame

**Comment by bilgili** [comment]
Apparently this fix requires different code paths for OSX and 2.1 and it is not a day of work. So, I am going to open a ticket with the information needed, if I have time after the transfer function, I can have a look more detailed. Issue #330

**Comment by bilgili** [comment]
@eile : Can you try again ?

**Comment by eile** [comment]
Now it's completely black. Does it work on Linux with GL2?

**Comment by eile** [comment]
Ah:
```
86168.Draw0    e/core/render/GLSLShaders.cpp:62     1923 Shader error: ERROR: 0:15: 'datatype' : syntax error syntax error

86168.Draw0    render/RayCastRendererGL2.cpp:114    1923 Can't load glsl shaders: Failed OpenGL operation returned GL_NO_ERROR in ../Livre/livre/eq/render/RayCastRendererGL2.cpp:114
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Can't load glsl shaders: Failed OpenGL operation returned GL_NO_ERROR in ../Livre/livre/eq/render/RayCastRendererGL2.cpp:114
```
Let me look into it.

**Pull request closed without merging**
